version: "3.9"

services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_DB: sside-net
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql
